#!/bin/bash

# ──────────────────────────────────────────────────────────────────────────────
# EnergyTune – Build IPA for TestFlight (upload via Transporter)
#
# Prerequisites:
#   1. Xcode 15+ installed (tested with Xcode 16.x)
#   2. Apple ID signed in to Xcode  (Settings → Accounts)
#   3. Apple Developer Program membership (paid)
#   4. App created in App Store Connect with bundle ID: energytune.app
#   5. CocoaPods installed  (gem install cocoapods)
#   6. npm dependencies: run npm install in the project root first (the script will
#      run npm install automatically if node_modules/expo is missing)
#   7. ios/ is generated by this script via prebuild (not committed; see .gitignore)
#
# What this script does:
#   • Increments expo.ios.buildNumber in app.json (required for each TestFlight upload)
#   • Optionally bumps expo.version patch (see --bump-expo-version)
#   • Runs expo prebuild --platform ios --clean
#   • Installs pods
#   • Verifies you have an Apple Distribution certificate (warns if missing)
#   • Archives a Release build with automatic signing
#   • Exports a properly signed IPA via xcodebuild -exportArchive
#   • Drops EnergyTune.ipa in the project root, ready for Transporter
#
# Team ID (never commit this — public repo):
#   • Copy .env.testflight.example → .env.testflight and set APPLE_TEAM_ID=XXXXXXXXXX
#     (.env.testflight is gitignored), or
#   • export APPLE_TEAM_ID=XXXXXXXXXX in your shell before running.
#   Find the value: Xcode → Settings → Accounts → your team, or developer.apple.com → Membership.
#
# Usage:
#   chmod +x build-testflight.sh
#   ./build-testflight.sh
#   ./build-testflight.sh --bump-expo-version   # also patch-bump expo.version in app.json
# ──────────────────────────────────────────────────────────────────────────────

# ── Paths (needed before loading local env) ──────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Optional local secrets: copy from .env.testflight.example (not committed)
ENV_FILE="${SCRIPT_DIR}/.env.testflight"
if [ -f "$ENV_FILE" ]; then
  set -a
  # shellcheck disable=SC1090
  . "$ENV_FILE"
  set +a
fi

# ── Configuration ─────────────────────────────────────────────────────────────
SCHEME="EnergyTune"
APP_NAME="EnergyTune"
BUNDLE_ID="energytune.app"

# ── Paths (continued) ─────────────────────────────────────────────────────────
WORKSPACE="${SCRIPT_DIR}/ios/${APP_NAME}.xcworkspace"
BUILD_DIR="${SCRIPT_DIR}/ios/build"
ARCHIVE_PATH="${BUILD_DIR}/${APP_NAME}.xcarchive"
EXPORT_DIR="${BUILD_DIR}/export"
BUILD_LOG="${BUILD_DIR}/build.log"
IPA_OUTPUT="${SCRIPT_DIR}/${APP_NAME}.ipa"
EXPORT_PLIST="${BUILD_DIR}/ExportOptions.plist"

BUMP_EXPO_VERSION=0
for arg in "$@"; do
  case $arg in
    --bump-expo-version) BUMP_EXPO_VERSION=1 ;;
  esac
done

# UTF-8 for CocoaPods / Ruby
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# ── Helpers ───────────────────────────────────────────────────────────────────
bold()  { printf "\033[1m%s\033[0m" "$1"; }
green() { printf "\033[1;32m%s\033[0m" "$1"; }
red()   { printf "\033[1;31m%s\033[0m" "$1"; }

step() { echo ""; echo "$(bold "[$1/$TOTAL_STEPS]") $2"; }

die() {
  echo ""
  echo "$(red "ERROR:") $1"
  shift
  for line in "$@"; do echo "  $line"; done
  echo ""
  echo "Full build log: ${BUILD_LOG}"
  exit 1
}

TOTAL_STEPS=7

TEAM_ID="${APPLE_TEAM_ID:-}"
if [ -z "$TEAM_ID" ]; then
  echo ""
  echo "$(red "ERROR:") APPLE_TEAM_ID is not set."
  echo ""
  echo "  For a public repository, do not hardcode your Team ID in this script."
  echo "  Either:"
  echo "    1. cp .env.testflight.example .env.testflight"
  echo "       Edit .env.testflight and set:  APPLE_TEAM_ID=Your10CharTeamID"
  echo "    2. Or run:  export APPLE_TEAM_ID=Your10CharTeamID"
  echo ""
  exit 1
fi

# ══════════════════════════════════════════════════════════════════════════════
echo ""
echo "$(bold '🚀 EnergyTune — TestFlight IPA Builder')"
echo "─────────────────────────────────────────────────"
echo ""

# ── Step 1: Bump iOS build number (and optionally marketing version) in app.json
step 1 "Bumping iOS build number in app.json"

command -v node >/dev/null 2>&1 || die "node not found. Install Node.js."

VERSION_OUT=$(node -e "
const fs = require('fs');
const appPath = process.argv[1] + '/app.json';
const bumpMarketing = process.argv[2] === '1';
const app = JSON.parse(fs.readFileSync(appPath, 'utf8'));
app.expo = app.expo || {};
app.expo.ios = app.expo.ios || {};
const raw = app.expo.ios.buildNumber;
const bn = parseInt(String(raw != null ? raw : '0'), 10);
const next = (Number.isFinite(bn) ? bn : 0) + 1;
app.expo.ios.buildNumber = String(next);
if (bumpMarketing) {
  const ver = (app.expo && app.expo.version) || '1.0.0';
  const parts = ver.split('.').map(Number);
  while (parts.length < 3) parts.push(0);
  parts[2] = (parts[2] || 0) + 1;
  app.expo.version = parts.slice(0, 3).join('.');
}
fs.writeFileSync(appPath, JSON.stringify(app, null, 2) + '\n');
const v = (app.expo && app.expo.version) || '';
process.stdout.write(next + ' ' + v + '\n');
" "$SCRIPT_DIR" "$BUMP_EXPO_VERSION") || die "Failed to run version bump script."
read -r NEW_BUILD_NUMBER NEW_EXPO_VERSION <<EOF
${VERSION_OUT}
EOF

if [ -z "$NEW_BUILD_NUMBER" ]; then
  die "Failed to update app.json build number."
fi

if [ "$BUMP_EXPO_VERSION" -eq 1 ]; then
  echo "  $(green '✓') iOS build number → ${NEW_BUILD_NUMBER}, expo.version → ${NEW_EXPO_VERSION}"
else
  echo "  $(green '✓') iOS build number → ${NEW_BUILD_NUMBER} (expo.version unchanged; use --bump-expo-version to patch bump)"
fi

# ── Step 2: Prebuild (ios/) ───────────────────────────────────────────────────
step 2 "Prebuild iOS (energytune.app)"

command -v npm >/dev/null 2>&1 || die "npm not found. Install Node.js (includes npm)."
command -v npx >/dev/null 2>&1 || die "npx not found. Install Node.js and npm."

if [ ! -d "${SCRIPT_DIR}/node_modules/expo" ]; then
  echo "  $(bold 'Note:') Local expo package missing — running npm install…"
  (cd "$SCRIPT_DIR" && npm install) \
    || die "npm install failed." \
           "From the project root run:  npm install"
fi

(cd "$SCRIPT_DIR" && npx expo prebuild --platform ios --clean) \
  || die "expo prebuild failed." \
         "Ensure app.json is valid and npm install completed (expo must live in node_modules)."

echo "  $(green '✓') ios/ generated with bundle ID ${BUNDLE_ID}"

# ── Step 3: Preflight checks ─────────────────────────────────────────────────
step 3 "Preflight checks"

command -v xcodebuild >/dev/null 2>&1 || die "xcodebuild not found. Install Xcode from the Mac App Store."
command -v pod        >/dev/null 2>&1 || die "CocoaPods not found." "Install with: sudo gem install cocoapods"

XCODE_VER=$(xcodebuild -version 2>/dev/null | head -1 || echo "unknown")
echo "  Xcode:     ${XCODE_VER}"
echo "  Team ID:   ${TEAM_ID}"
echo "  Bundle ID: ${BUNDLE_ID}"
echo "  Scheme:    ${SCHEME}"

if [ ! -d "$WORKSPACE" ]; then
  die "Workspace not found at ${WORKSPACE}" \
      "Run:  cd ios && pod install"
fi

# Check for Apple Distribution certificate
DIST_CERT=$(security find-identity -v -p codesigning 2>/dev/null \
  | grep -c "Apple Distribution" || true)

if [ "$DIST_CERT" -eq 0 ]; then
  echo ""
  echo "  $(bold 'WARNING:') No Apple Distribution certificate found in keychain."
  echo "  The build will attempt to create one automatically via Xcode."
  echo ""
  echo "  If that fails, create one manually:"
  echo "    Xcode → Settings → Accounts → your Apple ID →"
  echo "    Manage Certificates → (+) → Apple Distribution"
  echo ""
fi

# ── Step 4: Install CocoaPods dependencies ────────────────────────────────────
step 4 "Installing CocoaPods dependencies"

(cd "${SCRIPT_DIR}/ios" && pod install --silent) \
  || die "pod install failed." \
         "Try manually:  cd ios && pod install"

echo "  $(green '✓') Pods installed"

# ── Step 5: Clean previous artifacts ─────────────────────────────────────────
step 5 "Preparing build directory"

mkdir -p "$BUILD_DIR"
rm -rf "$ARCHIVE_PATH" "$EXPORT_DIR" "$IPA_OUTPUT" "$BUILD_LOG"
echo "  $(green '✓') Cleaned previous build artifacts"

# Generate ExportOptions.plist (kept in build dir so ios/ stays clean of ad-hoc plist)
cat > "$EXPORT_PLIST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>method</key>
  <string>app-store-connect</string>
  <key>teamID</key>
  <string>${TEAM_ID}</string>
  <key>signingStyle</key>
  <string>automatic</string>
  <key>uploadSymbols</key>
  <true/>
  <key>destination</key>
  <string>export</string>
</dict>
</plist>
PLIST

echo "  $(green '✓') Generated ExportOptions.plist"

# ── Step 6: Archive ───────────────────────────────────────────────────────────
step 6 "Archiving (this may take a few minutes…)"

ARCHIVE_START=$SECONDS

xcodebuild \
  -workspace "$WORKSPACE" \
  -scheme "$SCHEME" \
  -configuration Release \
  -sdk iphoneos \
  -destination "generic/platform=iOS" \
  -archivePath "$ARCHIVE_PATH" \
  -allowProvisioningUpdates \
  DEVELOPMENT_TEAM="$TEAM_ID" \
  CODE_SIGN_STYLE=Automatic \
  COMPILER_INDEX_STORE_ENABLE=NO \
  clean archive \
  > "$BUILD_LOG" 2>&1 \
  || {
    echo ""
    echo "$(red '✗') Archive failed!"
    echo ""
    echo "Key errors from build log:"
    grep -E "error:" "$BUILD_LOG" | grep -v "warning:" | head -15
    echo ""

    if grep -qi "no accounts\|sign in" "$BUILD_LOG"; then
      echo "→ Sign in to Xcode:  Xcode → Settings → Accounts → Add Apple ID"
    elif grep -qi "provisioning profile\|no profile\|no eligible" "$BUILD_LOG"; then
      echo "→ Signing issue. Make sure the app (bundle ID ${BUNDLE_ID}) is"
      echo "  registered in App Store Connect and your Team ID is correct."
    fi
    die "Archive step failed. See errors above."
  }

ARCHIVE_SECS=$(( SECONDS - ARCHIVE_START ))
echo "  $(green '✓') Archive succeeded (${ARCHIVE_SECS}s)"

# Quick sanity: does the archive contain an .app?
if [ ! -d "${ARCHIVE_PATH}/Products/Applications/${APP_NAME}.app" ]; then
  die "Archive exists but does not contain ${APP_NAME}.app." \
      "This usually means the scheme or app name is wrong."
fi

# ── Step 7: Export IPA ────────────────────────────────────────────────────────
step 7 "Exporting IPA for App Store / TestFlight"

mkdir -p "$EXPORT_DIR"

EXPORT_START=$SECONDS

xcodebuild \
  -exportArchive \
  -archivePath "$ARCHIVE_PATH" \
  -exportOptionsPlist "$EXPORT_PLIST" \
  -exportPath "$EXPORT_DIR" \
  -allowProvisioningUpdates \
  >> "$BUILD_LOG" 2>&1 \
  || {
    echo ""
    echo "$(red '✗') Export failed!"
    echo ""
    echo "Last 20 lines of build log:"
    tail -20 "$BUILD_LOG"
    echo ""

    if grep -qi "no applicable destination\|no accounts\|Unknown Distribution Error" "$BUILD_LOG"; then
      echo "──────────────────────────────────────────────────────────────────"
      echo "This usually means you're missing an Apple Distribution certificate."
      echo ""
      echo "Fix:  Open Xcode → Settings → Accounts → select your Apple ID"
      echo "      → Manage Certificates → click (+) → Apple Distribution"
      echo ""
      echo "Then run this script again."
      echo "──────────────────────────────────────────────────────────────────"
    fi
    die "Export step failed. See errors above."
  }

EXPORT_SECS=$(( SECONDS - EXPORT_START ))

# Locate the generated IPA
FOUND_IPA=$(find "$EXPORT_DIR" -name "*.ipa" -type f 2>/dev/null | head -1 || true)

if [ -z "$FOUND_IPA" ]; then
  die "Export completed but no .ipa file found in ${EXPORT_DIR}/"
fi

mv "$FOUND_IPA" "$IPA_OUTPUT"

# Verify the IPA contains a provisioning profile (Transporter requires it)
if unzip -l "$IPA_OUTPUT" 2>/dev/null | grep -q "embedded.mobileprovision" 2>/dev/null; then
  PROFILE_OK="yes"
else
  PROFILE_OK="no"
fi

IPA_SIZE=$(ls -lh "$IPA_OUTPUT" | awk '{print $5}')

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  $(green '✅  IPA built successfully!')"
echo ""
echo "  File:      ${IPA_OUTPUT}"
echo "  Size:      ${IPA_SIZE}"
echo "  Profile:   ${PROFILE_OK}"
echo "  Archive:   ${ARCHIVE_SECS}s"
echo "  Export:    ${EXPORT_SECS}s"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

if [ "$PROFILE_OK" = "no" ]; then
  echo "$(bold 'WARNING:') embedded.mobileprovision not found inside the IPA."
  echo "Transporter may reject this file. If so, create your Distribution"
  echo "certificate in Xcode and re-run this script."
  echo ""
fi

echo "$(bold 'Upload to TestFlight via Transporter:')"
echo "  open -a Transporter \"${IPA_OUTPUT}\""
echo ""
echo "Or drag & drop ${APP_NAME}.ipa into the Transporter app."
echo ""
